### PR TITLE
added ability to set last ffc time

### PR DESCRIPTION
**Pull request by gferraro**
using this you can skip the warmup-time

### CODE REVIEW

**Comment by clare** [comment]
It looks ok at a quick glance.  
A few thoughts I've had is:
* I probably would have used a FFC offset which defaults to 0.   That way the time since ffc would keep increasing (maybe a little more accurate if another FFc comes along).  But what you've done is fine.  
* the file fakecamera.go file is getting pretty long now.   Maybe it's time to split it up (eg split playing recorded data from fake data)
* I note you had to make the same change in two places (fake data / recorded data).   This is a bit of a code smell.   Maybe there is a better way to do it?

**Review by clare — APPROVED** [review]
See my comment earlier.

**Comment by clare** [comment]
GP this looks like a step in the right direction but it isn't quite working for me yet.   I tried to use this file this file https://github.com/feverscreen/fake-thermal-camera/blob/ee8624835d65a26627c53ed74324cffefc0039d1/fakecamera/cptv-files/person.cptv, and it is now telling me that I have to wait 30 minutes for my camera to warm up.

**Comment by gferraro** [comment]
> GP this looks like a step in the right direction but it isn't quite working for me yet. I tried to use this file this file https://github.com/feverscreen/fake-thermal-camera/blob/ee8624835d65a26627c53ed74324cffefc0039d1/fakecamera/cptv-files/person.cptv, and it is now telling me that I have to wait 30 minutes for my camera to warm up.

I dont get an error with that, but i fixed an issue about trying again in 30 seconds, and it should print out a better error.

The video was taken when the camera was on for less than 30 minutes. so would need to add a "time-on" override to fix the warm up banner. As far as i can tell it doesn't matter

**Pull request merged**
